name: Louwers
favicon: null
layout_spectrum: 0.21499599260278046
typography_spectrum: 0.52554
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#616265'
    - '#000000'
    - '#404040'
    - '#000080'
    - '#dbebf0'
  brandStrength: 0.8339710149448365
  lightness: 0.5
  saturation: 0.9325890636537224
  rhythmicContrast: 0.2189465907867998
purpose: []
