name: Louwers
favicon: null
layout_spectrum: 0.4019
typography_spectrum: 0.52554
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eff1ed'
    - '#879c50'
    - '#9b3f00'
    - '#677721'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.9325890636537224
  rhythmicContrast: 0.2189465907867998
purpose: []
